Api:
  Name: alger-api
  Host: 127.0.0.1
  Port: 8085
  Timeout: 5000


JwtAuth:
  AccessSecret: ad879037-c7a4-4063-9236-6bfc35d54b7d
  AccessExpire: 86400

Mysql:
  DataSource: root:alger@tcp(47.108.222.104:5306)/alger?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
  LogMode: true



Log:
  Type: zap
  Level: info
  FilePath: ./logs/
  FileName: alger-server.log
  MaxSize: 10
  MaxBackups: 30
  MaxAge: 15
  Compress: true
  LocalTime: true
  LogInConsole: true



